import streamlit as st
from streamlit_shap import st_shap
# importing the ai module
from ai_detection import ai_detector 

import shap 


st.title("NewsShield v1.0")
st.subheader("An app that can detect ai generated news articles")

left,right=st.columns(2)
with left:
    st.image("ny_times.jpg") 
with right: 
    st.write("This app aims to reduce misinformation that is rife within media outlets. By detecting misinformation, such as those generated by Large Language Models (LLM), such as ChatGPT and Google Gemini, news outlets can spread true information to the rest of the world.")
    
    
text = st.text_input('Please enter your text here:', 'Example news text')

news_to_classify = ai_detector(text) 

st.write(f"Prediction: {news_to_classify.predict()}... with confidence of {news_to_classify.predict_proba()}")

st.write("Explanation")
# I should include the explanation as an option
explain = st.checkbox("Explain the prediction...")

if explain:
  # I need to show this as a streamlit graph 
  # the streamlit plot is currently a waterfall plot 
  explain_plot = news_to_classify.explain()
  st_shap(explain_plot) 

# I can use a textbox


