import streamlit as st

# importing the ai module
from ai_detection import ai_detector 

import shap 


st.title("NewsShield v1.0")
st.subheader("An app that can detect ai generated news articles")

left,right=st.columns(2)
with left:
    st.image("ny_times.jpg") 
with right: 
    st.write("This app aims to reduce misinformation taht is rife within media outlets. By detecting misinformation, such as those generated by Large Language Models (LLM), such as ChatGPT and Google Gemini, news outlets can spread true information to the rest of the world.")
    
    
text = st.text_input('Please enter your text here:', 'Example news text')

news_to_classify = ai_detector(text) 

st.write(f"Prediction: {news_to_classify.predict()}... with confidence of {news_to_classify.predict_proba()}")

st.write("Explanation")

news_to_classify.explain()
# I can use a textbox


