# this workflow will summarise news articles once a day 

# this yml file will test the data collection of scripts/test_vinfast_data_collection.py 
#
#

name: Summarise News articles

on: 

  push: 
    branches: [main]
    
    paths: 
      - "scripts/create_reports.py" 
      - '.github/workflows/summarise_news_articles.yml'
  pull_request:
    branches: [main]

  schedule: 
    # run this workflow at 08:00 UTC once a week to check if the data collection
    # works
    - cron: '0 8 * * 1'
  
  # adding a manual "run workflow" button" 
  workflow_dispatch: {} 

jobs: 
  # name of the job 
  vinfast-stock-code-testing: 
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository 
        uses: actions/checkout@v4

      - name: Create streamlit secrets file
        env:
          groq_api_key: ${{ secrets.GROQ_API_KEY }}
        run: |
          mkdir -p .streamlit 
          echo "fin_historical_data = \"$groq_api_key\"" >> .streamlit/secrets.toml

      - name: Set up UV
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9


      - name: Set up Python 
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12.12'
          cache: 'pip'

      - name: Install dependencies
     # Also installing uv 
        run: |
          uv pip install --system -r requirements.txt

      - name: Summarise news articles
        # Is there a way to load only the load_vinfast_news function? 
        run: |
            python scripts/create_reports.py

# -----------------------------------------------------

      - name: Saving the summarised news data 
        run: |

            git config user.name "Thomas-Nguyen12"
            git config user.email "thomas.nguyen3612@gmail.com"
            git pull
            git add data/vinfast_news_data/summarised_news_articles.md
            git commit -m "Collected some news data" || echo "No changes to commit"
            git push
